# Generated by Django 3.2 on 2022-03-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_blog_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_snippet',
            field=models.CharField(default='Click Above to Read the Blog Post', max_length=200),
        ),
    ]
