# Generated by Django 3.2 on 2022-03-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_blog_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_snippet',
            field=models.CharField(max_length=200),
        ),
    ]
